did_django_google_maps_api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('main.urls', namespace="main")),
    path('admin/', admin.site.urls),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path 
from . import views

 
app_name = "main"

urlpatterns = [
	
	path('', views.route, name="route"),
	path('map', views.map, name="map"),
	# path('mail', views.Index.as_view(), name='index'),
	path('contact', views.contact_view.as_view(), name="contact"),
	# path('station', views.adresses, name="station"),
    path('station', views.AdresseAPIView.as_view(), name="station"),
	 
	path('station/<str:id>/', views.AdresseDetails.as_view(), name="station"),
     
	]

main/models.py
from django.db import models
from mongoengine import Document,fields
 

class Adresse(Document):
    location = fields.StringField()

    meta={
        'collection': 'station'
    }
     

main/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=200)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

     
 

main/views.py
from django.shortcuts import render
from django.conf import settings
from rest_framework.views import APIView
import math
from .mixins import Directions
from django.core.mail import send_mail
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import io, base64
from matplotlib.ticker import LinearLocator
import numpy as np 
from main.serializers import AdresseSerializer
from main.models import Adresse 
import json
from rest_framework.response import Response
from django.http import HttpResponse, HttpResponseRedirect
from rest_framework import status
from django.shortcuts import get_object_or_404
from .forms import ContactForm
from rest_framework.permissions import IsAuthenticated
from django.urls import reverse_lazy
from django.shortcuts import HttpResponseRedirect
from django.views.generic import TemplateView
from django import forms

'''
Basic view for routing 
'''
def route(request):
      
  
	context = {"google_api_key": settings.GOOGLE_API_KEY, 
	           "serializer":adresses()}
	return render(request, 'main/route.html', context)


'''
Basic view for displaying a map 
'''
def map(request):

	lat_a = request.GET.get("lat_a")
	long_a = request.GET.get("long_a")
	lat_b = request.GET.get("lat_b")
	long_b = request.GET.get("long_b")
	vitesse = request.GET.get("vitesse")
	soc= request.GET.get("soc") 
	# station = Adresses.objects.all()
	# waypoints=request.GET.get("waypoints")
	puissance_vehicule=voiture(int(vitesse)) 
	autonomie_soc_initial =autonomie_soc_minimal(puissance_vehicule,int(soc))
  
    
	directions = Directions(
		lat_a= lat_a,
		long_a=long_a,
		lat_b = lat_b,
		long_b=long_b
		)
 
	context = {
	"google_api_key": settings.GOOGLE_API_KEY,
	"lat_a": lat_a,
	"long_a": long_a,
	"lat_b": lat_b,
	"long_b": long_b,
	"origin": f'{lat_a}, {long_a}',
	"destination": f'{lat_b}, {long_b}',
	"directions": directions,
	"puissance_vehicule":puissance_vehicule, 
	"autonomie_soc_minimal":autonomie_soc_initial,
	"serializer":adresses()
	# "station":station
    # "waypoints":waypoints
	}
	return render(request, 'main/map.html', context)

def voiture(vitesse) :
	mass = 2000 #kgcd  
	mass_factor = 1.05
	acceleration = 0 # m^2 / s
	coeff_roll_R = 0.02  # coefficient of rolling resistance
	air_density = 1.225 # kg/m^3
	front_area = 2 # m^2
	aero_drag_coff = 0.5
	wind_speed = 0 # m/s
	road_angle = 0 # angle
	angle = 2       
	rad = math.radians(angle)
	p1 = (mass_factor * mass * acceleration) + (mass * 9.8 * coeff_roll_R * math.cos(rad))
	p2 = 0.5 * air_density * front_area * aero_drag_coff * ((vitesse -wind_speed)**2) # vitesse en m/S
	p3 = mass * 9.8 * math.sin(rad)
	puissance =round(((p1 + p2 + p3) * (vitesse/3.6) )/1000, 3) #kw
	return puissance

def batterie(puissance_vehicule, soc_initial, temps):
    
	capacite_totale =10 #KWH
	capacite_restante=(puissance_vehicule*temps)/3600  #KWH
	soc_batterie=soc_initial - (capacite_restante/capacite_totale )*100 # %
	return soc_batterie 

def autonomie_soc_minimal(puissance_vehicule, soc_initial):
	 
	capacite_totale =10 #KWH
	autonimie_soc_minimal=round(((36*capacite_totale*(soc_initial))/puissance_vehicule),2)
	return autonimie_soc_minimal

# def calcul(temps, soc_batterie):
	 
# 	fig, ax = plt.subplots(figsize=(10,4))
# 	ax.plot(temps,soc_batterie, '--bo')
# 	fig.autofmt_xdate()
# 	ax.fmt_xdata = mdates.DateFormatter('%Y-%m-%d')
# 	ax.set_title('Etat de décharge de la batterie')
# 	ax.set_ylabel("Soc (%)")
# 	ax.set_xlabel("Temps (min)")
# 	ax.set_ylim([0,110])
# 	ax.grid(linestyle="--", linewidth=0.5, color='.25', zorder=-10)
# 	ax.yaxis.set_minor_locator(LinearLocator(25))
# 	flike = io.BytesIO()
# 	fig.savefig(flike)
# 	b64 = base64.b64encode(flike.getvalue()).decode()
	 
# 	return b64

  
def adresses():


	qs1 = Adresse.objects.all()

	serializer = AdresseSerializer(qs1, many=True)
	
	pars = json.dumps(serializer.data,ensure_ascii=False)
	return pars
class ContactAPIView(APIView):

      def get(self, request):
          rq =Adresse.objects.all()
          serializer = AdresseSerializer(rq, many=True)
          return render(request, 'main/route.html', serializer.data)

      def post(self, request):
          serializer= AdresseSerializer(data=request.data)
          if serializer.is_valid():
              serializer.save()
			  
              return Response(serializer.data, status=status.HTTP_201_CREATED)
          return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)	

# 	return render(request,"main/index.html",{'serializer':pars})
 
    #  def post(self, request):
    #       serializer= AdresseSerializer(data=request.data)
    #       if serializer.is_valid():
        # serializer.save()
    #          return Response(serializer.data)
    #       return Response(serializer.errors) 
class AdresseAPIView(APIView):
    #   permission_classes = (IsAuthenticated, )
      def get(self, request):
          articles = Adresse.objects.all()
          serializer = AdresseSerializer(articles, many=True)
          return Response(serializer.data)

      def post(self, request):
          serializer= AdresseSerializer(data=request.data)
          if serializer.is_valid():
              serializer.save()
              return Response(serializer.data, status=status.HTTP_201_CREATED)
          return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class AdresseDetails(APIView):
    
	def get_object(self, id):
		try:
		  return Adresse.objects.get(id=id)
		except Adresse.DoesNotExist:
			return HttpResponse(status=status.HTTP_404_NOT_FOUND)

	def get(self, request, id):
		station =self.get_object(id)
		serializer = AdresseSerializer(station)
		return Response(serializer.data)

	def put(self, request, id):
		station=self.get_object(id)
		serializer= AdresseSerializer(station, data=request.data)
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data)
		return Response (serializer.errors, status=status.HTTP_400_BAD_REQUEST)
	def delete(self,request, id):
          article =self.get_object(id)
          article.delete()
          return Response(status=status.HTTP_204_NO_CONTENT)	

 
class contact_view(APIView): 
     
    def get(self, request):  
        donnees= ContactForm()  
        return render(request,"main/index.html",{'form':donnees})  

    def post(self, request):
        form= ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']

            recipients = ['hassanif19@gmail.com']
            if cc_myself:
               recipients.append(sender)

            send_mail(subject, message, sender, recipients)
            return HttpResponseRedirect('/thanks/')

# class Index(EmailMixin, TemplateView):
#     template_name = 'main/index.html'
#     email_template_name = 'main/sendMail.html'

#     def get_context_data(self, **kwargs):
#         """
#         Método para pegar o formulário e os dados submetidos.
#         Nota - Customize a estrutura de seu email no arquivo email.html
#         """
#         context = super(Index, self).get_context_data(**kwargs)
#         form = EmailForm()
#         # data example
#         data = dict()
#         data['email_to'] = self.request.POST.get('email_to')
#         data['title'] = self.request.POST.get('title')
#         data['message'] = self.request.POST.get('message')

#         context['form'] = form
#         context['data'] = data
#         return context

#     def post(self, request, *args, **kwargs):
#         self.send_mail()
#         return HttpResponseRedirect(reverse_lazy('main:index'))			

# def home(request):
#     return render(request,'home.html')

# class Home(TemplateView):
#     template_name = 'home.html'
# def home(request):
#     return render(request,'main/home.html')


# def send_gmail(request):
#     if request.method=="POST":
#         name = request.POST.get('name')
#         subject = request.POST.get('subject')
#         message = request.POST.get('message')
#         print(name, subject, message)

#         send_mail(
#             subject,
#             message,
#             'hassanif19@gmail.com',
            
#             fail_silently=False,
#         )

#         return HttpResponseRedirect(reverse('main/home'))
#     else:
#         return HttpResponse('Invalid request')		

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- visit https://fonts.google.com/specimen/Courier+Prime?preview.text_type=custom to get script-->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'main.css' %}"></link>

  <!-- This allows us to extend the head scripts in HTML docs that have special requirements-->
  {% block extend_head %}

  {% endblock %}

</head>
<body>

  <!-- This allows us to extend the nav bar in HTML docs that have special requirements-->
  {% block extend_nav %}

  {% endblock %}

  <div class="div-container">
    
  <!-- {% include 'main/partials/logo.html' %}-->

    {% block content %}

    {% endblock %}

  </div>

  <!--visit https://code.jquery.com/ for jquery script-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

  <!-- This allows us to extend the foot scripts in HTML docs that have special requirements-->
  {% block extend_footer %}

  {% endblock %}

  <script src="{% static 'main.js' %}"></script>
  

</body>
</html>

main/templates/main/index.html
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>FibroTex</title>
        <link rel="stylesheet" href="{% static 'boostrap.min.css' %}"></link>
   
    </head>
    <body>
        <div class="container" style ="background-color:silver;" > 
            <h3 class="mb-0" style="margin-top:70px;">Contactez-nous</h3> 
        <form method="post" action="mailto:hassanif19@gmail.com">
            {{ form.non_field_errors }}
            <div class="row mb-2">
                <div class="col-md-6" style="margin-top:40px;">
                    <div class="col-sm-6" >
                        {{ form.subject.errors }}
                        <label for="{{form.subject.id_for_label}}" class="form-label">Nom:</label>
                        <div> {{ form.subject }} </div>
                        
                        
                    </div>
                    
                    <div class="col-sm-6">
                        {{ form.sender.errors }}
                        <label for="{{ form.sender.id_for_label }}"  class="form-label">Email :</label>
                        <div>
                        {{ form.sender }}
                        </div> 
                    </div>
                   
                    <div class="col-sm-6">
                        {{ form.message.errors }}
                        <label for="{{ form.message.id_for_label }}"  class="form-label">Votre message :</label>
                        <div>
                        {{ form.message }}
                        </div>
                    </div>

                    <div class="col-sm-6">
                        {{ form.cc_myself.errors }}
                        <label for="{{ form.cc_myself.id_for_label }}">Envoyer une copie à moi méme</label>
                        {{ form.cc_myself }}
                    </div>
                    <input type="submit" value="Envoyer" />
                </div>
            </div>       
        </form>    




         

              <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
              integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
              crossorigin="anonymous"></script>
          <script src="https://kit.fontawesome.com/a076d05399.js"></script>
          <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
              integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
              crossorigin="anonymous"></script> 
          <script> $('.carousel').carousel({  pause: "null"  })  </script>  
           
   </body>

</html>

main/templates/main/map.html
{% extends 'main/base.html' %}
{% load static %}


{% block extend_head %}

<script src='https://www.google.com/recaptcha/api.js?render={{recaptcha_site_key}}'></script>


{% endblock %}

{% block extend_nav %} 

<ul class="sidenav">
  <li style="display: block;margin-top: 20px; padding: 0px;"><a  href="{% url 'main:route' %}">Informations de l'usager</a></li>
  
  
 
  <li style="display: block;margin-top: 0px; padding: 20px;margin-left: 80px;"><h2>Autonomie</h2> <br> <br>
    <div class="col-size" style="width: 50%;text-align: center; font-size: 20px;
    padding: 5% 0 0 0 !important;
    background: #07b6998f;">
    {{autonomie_soc_minimal}} minutes
    </div>  
<!--   
  <li style="display: block;margin-top: 0px; padding: 20px;">:<br> {{autonomie_soc_minimal}} minutes</li>
  <li style="display: block;margin-top: 20px; padding: 20px;"> -->
    <!-- <div id="right-panel"></div>
      <p>Total Distance: <span id="total"></span></p>
    </div> -->
    <!-- <div id="directions-panel"></div> -->
    <!-- <div  >
      <p>Total Distance: <span id="total"></span></p>
    </div> -->
     
    <li style="display: block; padding: 20px;margin-left: 20px;"><h2>Scénarios de test<h2></li> 
      <!-- <i>Sélectionner un scénario de test</i> <br /><br /> -->
   
     
     <a  href="#" title="SOC 20%"><input  type="submit" class="button_active" id="scenarioTest" value="Scénario 1"></a> 
    
    
    <a  href="#" title="Surconsommation de la batterie"><input  type="submit" class="button_active" value="Scénario 2"></a> 
      
    <a href="#" title="Mouvaise conduite"><input  type="submit" class="button_active" value="Scénario 3"></a>  
  
    <a  href="{% url 'main:contact' %}" title="SOC 20%"><input  type="submit" class="btn" id="sc " value="Espace admin"></a> 
    <a  href="{% url 'main:station' %}" title="SOC 20%"><input  type="submit" class="btn" id="sc " value="Contactez-nous"></a>  
   
     
  </l i > 
  
 
  <!-- <li style="display: block;margin-top: 0px; padding: 20px;">STATION :<span id="adr">{{serializer}}</span> </li> -->
</ul> 
  
 
<!-- <img src='data:image/png;base64,{{ chart }}'> -->
{% endblock %}


{% block content %}

<!-- <h3 id="map">Alertes/Recommandations</h3> -->

<div class="container">
  
  </table>

</div>

<div class="map-container">
  <p   id="listStations"> 
   
    {{serializer}} 
    
 
 </p> 
   <div  id="map-route">
   
   </div>


</div>

{% endblock %}

{% block extend_footer %}


<script type="text/javascript">

    var google_api_key = "{{google_api_key|safe}}";
    var lat_a = "{{lat_a|safe}}";
    var long_a ="{{long_a|safe}}";
    var lat_b = "{{lat_a|safe}}";
    var long_b = "{{long_b|safe}}";
    var origin = "{{origin|safe}}";
    var destination = "{{destination|safe}}";
    // var directions = {{directions|safe}}

  </script>

  <script src="{% static 'google_maps.js' %}"></script>


{% endblock %}

main/templates/main/route.html
{% extends 'main/base.html' %}
{% load static %}


{% block extend_head %}

<script src='https://www.google.com/recaptcha/api.js?render={{recaptcha_site_key}}'></script>

{% endblock %}

{% block extend_nav %} 

<ul class="sidenav">
  <li style="display: block;margin-top: 20px; padding: 0px;"><a class="active" href="{% url 'main:route' %}">Informations de l'usager</a></li>
  <!-- <li><a href="javascript:void(0)" onclick="alert('Please add a start and end address')">Test d'autonomie</a></li> -->
   
  <li  style="display: block;margin-top: 10px; padding: 15px;"> 
    <div>
      <span id="rangeValue">0</span>
      <Input id="soc_id" class="range" type="range" name "" value="0" min="0" max="100" onChange="rangeSlide(this.value,'rangeValue')"></Input>
      <label   for="customRange" class="form-label">SOC initial %</label>
    </div>
 
    <div>
      <span id="rangeValue1">0</span>
      <Input id="vitesse_id" class="range" type="range" name "" value="0" min="0" max="200" onChange="rangeSlide(this.value,'rangeValue1')"></Input>
      <label for="customRange" class="form-label">Vitesse Km/h</label>
    </div>
      
  
    <div>
      <span id="rangeValue2">25</span>
      <Input class="range" type="range" name "" value="0" min="-50" max="50" onChange="rangeSlide(this.value,'rangeValue2')" ></Input>
      <label  for="customRange3" class="form-label">Température °C</label>
    </div>
   <script type="text/javascript">
      function rangeSlide(value,id) {
          document.getElementById(id).innerHTML = value;
 
      }
   </script>      
  </li> 
   
  <input  style=" background-color:#0770b6c0; 
  border-radius: 15px;font-size: 18px;
  margin-left:80px;
  inline-size:160px;
  margin-top:60px;
  color: white; 
  padding: 10px;"  type="submit" id="submit"> 
  </li>
  <a  href="{% url 'main:station' %}"><input  type="submit" class="btn_admin" id="ctc " value="Espace admin"></a> 
  <a  href="{% url 'main:contact' %}" ><input  type="submit" class="btn_admin" id="ctc" value="Contactez-nous"></a> 
 
</li>
</ul>
 
 
 
{% endblock %}


{% block content %}

<h2>Entrer vos adresses de départ et de destination</h2>

<div class="container">

   <label for="id-google-address-a">Adresse de départ</label>
   <input type="text" placeholder="*Rechercher" id="id-google-address-a" name="google_address_a">

   <label for="id-google-address-b">Adresse de destination</label>
   <input type="text" placeholder="*Rechercher" id="id-google-address-b" name="google_address_b">


   <input type="hidden" class="geo" id="id-lat-a" value="">
   <input type="hidden" class="geo" id="id-long-a" value="">
   <input type="hidden" class="geo" id="id-lat-b" value="">
   <input type="hidden" class="geo" id="id-long-b" value="">


</div>
<div>
<img src="https://d1b9m7lmejcu5w.cloudfront.net/images/cimg/testreports/artikel11733-bild04-so-ist-der-porsche-panamera-s-e-hybrid-technisch-aufgebaut.jpg" alt="" style="width:700px;height:400px;padding-left: 100px ;">
</div>
{% endblock %}

{% block extend_footer %}


<script type="text/javascript">

    var google_api_key = "{{google_api_key|safe}}";

  </script>

  <script src="{% static 'google_places.js' %}"></script>


{% endblock %}

<!-- cd C:\Users\hassa\env\Scripts    .\activate    -->
<!-- cd C:\Users\hassa\Desktop\app_version1\django_map   python manage.py runserver -->
<!-- cd C:\Users\hassa\env\Scripts    .\activate    -->
<!-- cd C:\Users\hassa\Desktop\MyApplication\django_map  python manage.py runserver -->